/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2014-01-09 16:02:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>A real safe and high performant portal</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"stylesheets/master.css\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <script src=\"js/jquery-1.7.2.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"js/popup.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jqpopup.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<ul id=\"navigation\">\n");
      out.write("    <img src=\"img/logo.png\" width=\"100%\"/>\n");
      out.write("    <li><a href=\"/secu/\">Start / Main</a></li>\n");
      out.write("    <li><a href=\"search.secu\">search the web</a></li>\n");
      out.write("    <li><a href=\"picturegallery.secu\">watch beautiful pictures</a></li>\n");
      out.write("    <li><a href=\"login.secu\">login into area42 </a></li>\n");
      out.write("    <li><a href=\"mailing.secu\">mailinglist</a></li>\n");
      out.write("    <li><a href=\"newsletter.secu\">newsletter</a></li>\n");
      out.write("    <li><a href=\"help.secu\">FAQ / Helptopics</a> </li>\n");
      out.write("</ul>\n");
      out.write("\n");
      out.write("<div id=\"Inhalt\">\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
